const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('node:fs');const {spawn}=require('node:child_process');const assert=require('node:assert/strict');
const path=require('node:path');const os=require('node:os');
const port=process.env.RP_TEST_PORT||'17334';
const base='http://127.0.0.1:'+port;
const project=path.resolve(__dirname,'..');
const root=path.join(project,'rp_creator','static')+path.sep;
const testData=fs.mkdtempSync(path.join(os.tmpdir(),'rp-ui-'));
const server=spawn(process.env.PYTHON||(process.platform==='win32'?'python':'python3'),['-m','rp_creator','--port',port,'--data',testData],{cwd:project});
process.on('exit',()=>server.kill());
server.on('exit',()=>{try{fs.rmSync(testData,{recursive:true,force:true})}catch{}});
(async()=>{
 await new Promise((resolve,reject)=>{server.stderr.on('data',d=>{if(d.toString().includes('Uvicorn running'))resolve()});server.on('exit',code=>reject(Error('server stopped '+code)));setTimeout(()=>reject(Error('server did not start')),5000).unref()});
 const vc=new VirtualConsole();let errors=[];vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(fs.readFileSync(root+'index.html','utf8'),{url:base,runScripts:'outside-only',virtualConsole:vc});const w=dom.window;
 w.fetch=(url,options={})=>{const opts={...options};delete opts.signal;return fetch(new URL(url,base),opts)};
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.eval(fs.readFileSync(root+'app.js','utf8'));
 const wait=async(fn)=>{for(let i=0;i<300;i++){if(fn())return;await new Promise(r=>setTimeout(r,20))}throw Error('UI wait failed: '+w.document.body.textContent.slice(-2000))};
 const q=s=>w.document.querySelector(s);const click=s=>{assert(q(s),'Missing '+s);q(s).click()};
 const submit=s=>q(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>q('[data-action="new-campaign"]'));
 click('[data-tab="settings"]');await wait(()=>q('#settings-form'));
 q('[name=provider]').value='demo';submit('#settings-form');await wait(()=>q('#toast').textContent.includes('Conexão salva'));
 click('[data-action=new-campaign]');q('[name=name]').value='Mundo teste UI';submit('#campaign-form');await wait(()=>q('#chat-form'));
 const select=q('#npc-select');select.value=[...select.options].find(o=>o.textContent==='Sara').value;select.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>q('#message-input')&&!q('#message-input').disabled);
 q('#message-input').value='Eu odeio café e adoro chá de hibisco.';submit('#chat-form');await wait(()=>q('.message.npc'));
 assert(w.document.body.textContent.includes('Demonstração'));console.log('PASS create campaign, configure AI, select NPC, send chat');
 const mode=q('#npc-select');mode.value='__group__';mode.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>q('.group-mentions'));
 q('#message-input').value='@Sara oi';submit('#chat-form');await wait(()=>q('.group-message')&&w.document.body.textContent.includes('@Sara oi'));
 assert(w.document.body.textContent.includes('Sem @: todos respondem. Com @Nome: só o personagem marcado responde.'));console.log('PASS group scene and @ mention');
 click('[data-tab=memory]');await wait(()=>q('#memory-results'));assert(q('#memory-results').textContent.includes('hibisco'));
 click('[data-action=memory-detail]');await wait(()=>q('#modal-content').textContent.includes('Origem:'));click('[data-action=close]');console.log('PASS memories and evidence dialog');
 click('[data-tab=world]');await wait(()=>q('[data-action=new-location]'));click('[data-action=new-location]');q('[name=name]').value='Farol';q('[name=description]').value='Um farol à beira-mar';submit('#location-form');await wait(()=>[...w.document.querySelectorAll('h2')].some(x=>x.textContent==='Farol'));
 click('[data-action=new-npc]');q('[name=name]').value='Lia';q('[name=profile]').value='Uma bibliotecária observadora.';q('[name=goals]').value='Catalogar livros';q('[name=routine]').value='10 | Biblioteca | organiza livros';submit('#npc-form');await wait(()=>w.document.body.textContent.includes('Lia'));console.log('PASS location and NPC creation');
 click('[data-tab=scene]');await wait(()=>q('[data-action=advance]'));click('[data-action=advance]');await wait(()=>q('.scene-banner')&&w.document.body.textContent.includes('10:00'));console.log('PASS clock advance');
 click('[data-tab=vault]');await wait(()=>q('[data-action=vault-export]'));click('[data-action=vault-export]');await wait(()=>q('#vault-result')?.textContent.includes('Pasta do vault'));console.log('PASS vault export');
 assert.equal(errors.length,0,errors.join('\n'));console.log('DOM integration complete; no JS exceptions.');dom.window.close();server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
